// ------------------MOCKER--------------------
// DO NOT EDIT THIS FILE, CODE AUTO-GENERATED
// ------------------MOCKER--------------------

package mocks

import (
	"testing"

	"github.com/stretchr/testify/mock"
)

func MockExecutePerson(mocking *mock.Mock) *mock.Call {
	return mocking.On("ExecutePerson")
}

func AssertExecutePerson(mocking *mock.Mock, times int) {
	mocking.AssertNumberOfCalls(t, "ExecutePerson", times)
}

func MockGetPerson(mocking *mock.Mock, expectedReturns ...interface{}) *mock.Call {
	return mocking.On("GetPerson").Return(expectedReturns)
}

func AssertGetPerson(mocking *mock.Mock, times int, expectedReturns ...interface{}) {
	if times != 0 {
		mocking.AssertCalled(t, "GetPerson", expectedReturns)
	}

	mocking.AssertNumberOfCalls(t, "GetPerson", times)
}

func MockPostPerson(mocking *mock.Mock, expectedReturns ...interface{}) *mock.Call {
	return mocking.On("PostPerson",
		mock.AnythingOfType("person *Person"),
		mock.AnythingOfType("ctx context.Context"),
	).Return(expectedReturns)
}

func AssertPostPerson(mocking *mock.Mock, times int, expectedReturns ...interface{}) {
	if times != 0 {
		mocking.AssertCalled(t, "PostPerson", expectedReturns)
	}

	mocking.AssertNumberOfCalls(t, "PostPerson", times)
}

func MockUpdatePerson(mocking *mock.Mock, expectedReturns ...interface{}) *mock.Call {
	return mocking.On("UpdatePerson",
		mock.AnythingOfType("person *Person"),
		mock.AnythingOfType("ctx context.Context"),
	).Return(expectedReturns)
}

func AssertUpdatePerson(mocking *mock.Mock, times int, expectedReturns ...interface{}) {
	if times != 0 {
		mocking.AssertCalled(t, "UpdatePerson", expectedReturns)
	}

	mocking.AssertNumberOfCalls(t, "UpdatePerson", times)
}
